[package]
name = "vers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
itertools = "0.12.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.193"
